### ISSUE TITLE
Category agnostic explaination

### ISSUE THREAD

**Issue by meghalD** [YoungXIAO13/PoseFromShape#20]
Can someone explain as to how 3D shape information addition is helpful in generalization. The paper just says it does but does not explain a reason for the same. With respect to deep learning please elaborate on how it is able to generalize by just using multiview?

**Comment by likaiucas** [comment]
model link is not avaliable.

**Comment by YoungXIAO13** [comment]
> model link is not avaliable.

Hi @CoolbreezeKevin ,

I just tried the model download [links](https://github.com/YoungXIAO13/PoseFromShape/blob/490318620354ab5306c8f37439ccb6c7918953bc/model/download_models.sh#L10-L14), they work fine.

If you have error message says ```wget: unable to resolve host address ‘www.dropbox.com’```. 
Maybe you need to check with your network on how to correctly configure the port number.

**Comment by likaiucas** [comment]
got it, thanks your reply~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月10日(星期二) 下午3:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YoungXIAO13/PoseFromShape] Category agnostic explaination (#20)





  
model link is not avaliable.
  
Hi @CoolbreezeKevin ,
 
I just tried the model download links, they work fine.
 
If you have error message says wget: unable to resolve host address ‘www.dropbox.com’.
 Maybe you need to check with your network on how to correctly configure the port number.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
